version: '3.7'
services:
  mysql:
   image: postgres:latest
   ports:
     - '8080:8080'
   volumes:
     - ./data:/var/lib/postgres
   environment:
     - POSTGRES_RANDOM_ROOT_PASSWORD=yes
     - POSTGRES_DATABASE=app
     - POSTGRES_USER=app
     - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef